import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import Providers from "@/components/layouts/Providers";



const montserrat  = Montserrat ({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Relax - Tu espacio de bienestar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${montserrat.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
